#!/usr/bin/python

import sys, argparse, errno, os, shutil, subprocess

supported = ['ext4', 'xfs', 'btrfs', 'f2fs', 'gfs2', 'hfsplus', 'reiserfs', 'fat', 'sdcardfs']
no_copy = ['btrfs', 'f2fs']

def cmd(command, check=False, shell=True):
    print(command)
    if check is False:
        subprocess.call(command, shell=shell)
    else:
        subprocess.check_call(command, shell=shell)

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('-t', dest='type')
  parser.add_argument('-c', action='store_true')
  # parser.add_argument('-o', dest='object')

  args = parser.parse_args()

  if args.type is None or args.type not in supported:
    print('Please set valid type')
    sys.exit(1)

  # if args.object is None or args.object not in ['fsfuzz', 'executor']:
  #   print 'Please set valid object'
  #   sys.exit(1)

  if args.c:
    cmd('make mrproper', check=True)
    cmd('make -C tools/lkl clean', check=True)

  # copy config
  cmd('cp -f %s-config arch/lkl/configs/defconfig' % args.type)

  if args.type in no_copy:
    cmd('cp -f combined-consistency-no_copy.cpp tools/lkl/combined-consistency.cpp')
    cmd('cp -f shm-combined-consistency-no_copy.cpp tools/lkl/shm-combined-consistency.cpp')
  else:
    cmd('cp -f combined-consistency-copy.cpp tools/lkl/combined-consistency.cpp')
    cmd('cp -f shm-combined-consistency-copy.cpp tools/lkl/shm-combined-consistency.cpp')  

  # compile with instrumenting gcc
  dir_path = os.path.dirname(os.path.realpath(__file__))
  cmd('make -C tools/lkl LKL_FUZZING=1 -j CC=clang-16 CXX=/usr/local/bin/afl-clang-fast++')

  # copy object file
  cmd('cp -f tools/lkl/executor tools/lkl/%s-executor' % args.type)
  cmd('cp -f tools/lkl/combined tools/lkl/%s-combined' % args.type)
  cmd('cp -f tools/lkl/combined-consistency tools/lkl/%s-combined-consistency' % args.type)
  cmd('cp -f tools/lkl/shm-combined-consistency tools/lkl/%s-shm-combined-consistency' % args.type)
